### ISSUE TITLE
Frequent `ShutdownSignalException: connection error`

### ISSUE THREAD

**Issue by orium** [ITV/bucky#46]
With bucky 2.0.0-M7 we seem to have frequent `ShutdownSignalException` errors in a consumer.

```text
com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:918)
	at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:908)
	at com.rabbitmq.client.impl.AMQConnection.handleFailure(AMQConnection.java:708)
	at com.rabbitmq.client.impl.AMQConnection.access$400(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:607)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:598)
```

If this is not something trivially reproducible please let me know so I can try to figure out the conditions that lead to this.

**Comment by cmcmteixeira** [comment]
Hi @orium , could you provide some more context as to when this happens and provide some code examples of how you're using bucky ?
